### ISSUE TITLE
is there any firmware which supports open source hardware. 

### ISSUE THREAD

**Issue by anupsinha1** [Autodesk/machine-collaboration-utility#1]
Is there any hardware which is open source and which support open source firmware for multy head 3d printing
so you mention here. 
we would love to work on this new technology of 3d printing for an smart and amazing 3d printing industry

**Comment by mickbalaban** [comment]
we (printrbot) are using printrboard, which is supported, and is open source (hardware and firmware)

You can find printrboard info here:
https://github.com/Printrbot/printrboard

and firmware:
https://github.com/Printrbot/Marlin/tree/prod-platformio-2017

**Comment by anupsinha1** [comment]
you have firmware for this multi head printer .

**Comment by mickbalaban** [comment]
firmware is standard Marlin, nothing special about it

**Comment by anupsinha1** [comment]
and which slicer we use for this multi head printing.

**Comment by mickbalaban** [comment]
netfabb

**Comment by anupsinha1** [comment]
i am confused about that
how can i calibrate marlin firmware for multi head printer 
and slicer ..

**Comment by anupsinha1** [comment]
do you have calibrated  marlin firmware for 4 head printer.

**Comment by faeton13** [comment]
have you read "FRD_Documents"?

**Comment by matthova** [comment]
@anupsinha1 Netfabb, which is a piece of software separate from this Github repo, supports slicing meshes for an arbitrary sized build plate and an arbitrary n-headed multi-head 3d printer. The file generated by Netfabb creates Marlin-flavor GCode that can be consumed by Machine-Collaboration-Utility. There is currently no official or unofficial list of 3rd party vendors that sell Escher capable 3d printers.

I will add appropriate information to the README.md file on this repo as more information becomes available. Additionaly, infomation on Escher Hardware officially supported by Netfabb will most likely become availble here: https://www.netfabb.com/products/print-engines
