### ISSUE TITLE
download link to MCU rpi image doesn't work

### ISSUE THREAD

**Issue by rooiejoris** [Autodesk/machine-collaboration-utility#14]
Hi,

The download link to MCU rpi image in the wiki doesn't work
https://drive.google.com/open?id=0B7k-k73S74JBcVV0R2lOSEtLelE

I get a "not found error 404"

cheers / joris

**Comment by matthova** [comment]
@rooiejoris Thanks for the catch, I'll patch that. In the meantime, please check out the mcu image link available on the main readme page, aka https://drive.google.com/uc?id=0B7k-k73S74JBYUJkNjlvdEl6WWs&export=download
