### ISSUE TITLE
Controller board setup for Multi-Gantry FFF

### ISSUE THREAD

**Issue by therealxani** [Autodesk/machine-collaboration-utility#27]
Dear Ladies and Gentlemen, especially Matt Hova,

I am writing here regarding the Netfabb implemented Escher Multi-Gantry FFF Engine.
For an educational project at my university, I am confronted with the task to set up a 3D-printer using this exciting new technology.
After reading the Netfabb/Autodesk Help guide, containing information about Machine Collaboration Utility prerequisites and resources, also reading the Github wiki and FRD Documents provided here, there are still some questions i could not find an answer to:

-It is stated, that the MCU setup only supports Marlin-firmware. („and similar serial based CNC- firmware“ is mentioned) 
Does that mean, that it only supports 8-bit (Arduino-based) Controller boards, or does it also support Smoothieware or Repetier-firmware? 
For the Multi-Gantry setup, is there a recommendation regarding the Controller board?

-If I understood it right, besides the MCU RaspberryPis, there is a Controller board for each gantry intended. How do they have to be set up, are they connected to the MCUs via USB, and how does the Marlin-Firmware has to be configured? Are they just controlled by the „Conductor“-RaspberryPi via the MCU-Pis?

- Which Controller board is responsible for the Heatbed control?

I would be very thankful if you could provide me with the information needed, and I am looking forward to your response.

Best regards,

Alexander Strobl

**Comment by matthova** [comment]
@therealxani Apologies for the delayed response.

MCU can work with any firmware that consumes gcode, however we only actively support firmware with the same communication and command protocol as Marlin, such as Smoothieware and Repetier-firmware.

Each conductor player needs to be on the same network. They communicate over http web requests.

Currently the heatbed is not a part of Escher control, but rather something that the user takes care of separately. However, a user could set M104 and M140 commands as a part of the start sequence.

Also, we've created a slack channel for active discussions. Please feel free to ask more questions [here](https://mcu-community.herokuapp.com/).
