### ISSUE TITLE
Conductor wont allow addition of players to MCU

### ISSUE THREAD

**Issue by genpar** [Autodesk/machine-collaboration-utility#38]
In the latest update v1.8.0 when logging onto MCU through a Pi 3 as a conductor. The add player button is faded out and wont allow an addition of a player to the system. 

If I revert back to v1.5.0 for the conductor and still use v1.8.0 for the players, I can add players and control them as intended.

**Comment by matthova** [comment]
Thanks for reporting. The fix is now available in the master branch.
