### ISSUE TITLE
image 1.8.1 cant cancel the connected players stuck on the disconnecting and connecting tab

### ISSUE THREAD

**Issue by satveer-singh** [Autodesk/machine-collaboration-utility#44]

**Comment by matthova** [comment]
Can you include a screenshot or a log?
Can you show what url you are using for each printer?

**Comment by satveer-singh** [comment]
wait i am connecting now to the system

**Comment by satveer-singh** [comment]
![image](https://user-images.githubusercontent.com/34333619/50348016-a0d63100-055d-11e9-9573-4294a6c566ae.png)

**Comment by satveer-singh** [comment]
![image](https://user-images.githubusercontent.com/34333619/50348076-bea39600-055d-11e9-85a2-d570f8297a3c.png)

**Comment by matthova** [comment]
Do you have a separate raspberry pi for each bot?

**Comment by satveer-singh** [comment]
i have total three raspberry pis one for conductor and 2 for each bot
but for testing purpose i am using only one bot as of now and trying to connect to it

**Comment by matthova** [comment]
Per https://github.com/Autodesk/machine-collaboration-utility/wiki/07---Setting-up-Conductor step 4, the Conductor should set up bot1 with the endpoint `http://bot1.local/v1/bots/solo`

**Comment by matthova** [comment]
@satveer-singh did this resolve your connection issue or is there still an outstanding problem related to this issue?

**Comment by satveer-singh** [comment]
Hello thanks for response i just connected all the pis and it has added all
the players properly just stuck on printing the file its the test file just
stuck on 0 percent and terminal doesnt show any response i powered the
gantry and try to jog it moves but stuck aftetwards

**Comment by satveer-singh** [comment]
yes it resolved thanks
